version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"  # đảm bảo có dòng này để mở cổng
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname